### ISSUE TITLE
运行proxy-server报错

### ISSUE THREAD

**Issue by wucaizi** [CC11001100/ast-hook-for-js-RE#1]
if (!scriptArray?.length) {
                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)

**Comment by FreaxW** [comment]
+1

**Comment by FreaxW** [comment]
if (!node.declarations?.length) {
                                   ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\Projects\JavaScript\ast-hook-for-js-RE\src\api-server\api-server.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by CC11001100** [comment]
这是因为使用了node高版本的语法，高版本支持一个链式操作来判空，类似于这样：
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/%E5%8F%AF%E9%80%89%E9%93%BE

具体的node版本我也记不清了，要不就直接更新到最新的LTS版本算了，我找找node的版本更新日志确定了版本放到文档提醒一下，感谢反馈！

**Comment by CC11001100** [comment]
更新node版本到14.0.0+，建议更新到最新的LTS版本。

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.0.0
