### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by perfectplug** [CC11001100/ast-hook-for-js-RE#19]
C:\code\ast-hook-for-js-RE-master\src\api-server>node api-server.js
启动成功
PayloadTooLargeError: request entity too large
    at readStream (C:\code\ast-hook-for-js-RE-master\node_modules\raw-body\index.js:155:17)
    at getRawBody (C:\code\ast-hook-for-js-RE-master\node_modules\raw-body\index.js:108:12)
    at read (C:\code\ast-hook-for-js-RE-master\node_modules\body-parser\lib\read.js:77:3)
    at rawParser (C:\code\ast-hook-for-js-RE-master\node_modules\body-parser\lib\types\raw.js:81:5)
    at Layer.handle [as handle_request] (C:\code\ast-hook-for-js-RE-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\code\ast-hook-for-js-RE-master\node_modules\express\lib\router\index.js:317:13)
    at C:\code\ast-hook-for-js-RE-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\code\ast-hook-for-js-RE-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\code\ast-hook-for-js-RE-master\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\code\ast-hook-for-js-RE-master\node_modules\express\lib\middleware\init.js:40:5)

请教大佬，这个问题需要如何解决

**Comment by CC11001100** [comment]
node的http服务接受的请求体太大：
在这里：  
https://github.com/CC11001100/ast-hook-for-js-RE/blob/1a5f1a4e6a76ad3f7627559d0a04af26d439fef1/src/api-server/api-server.js#L7-L15  
增大限制，修改为：
```js
app.use(bodyParser.raw({
    verify: function (req, res, buf, encoding) {
        if (buf && buf.length) {
            req.rawBody = buf.toString();
        }
    }, type: function () {
        return true
    },
    limit: "100MB"
}));
```

已知问题，会随后续版本修复。

**Comment by perfectplug** [comment]
过于优秀

**Comment by perfectplug** [comment]
完美的解决了我碰到的问题
