### ISSUE TITLE
钩子未定义

### ISSUE THREAD

**Issue by drain** [CC11001100/ast-hook-for-js-RE#23]
首先，我不会说中文，我正在使用谷歌翻译，所以如果这很难理解，我深表歉意。我已按照您的自述中的步骤操作，但在设置代理后显示未定义钩子。

![image](https://user-images.githubusercontent.com/52178607/139909899-9c487968-251f-4403-8a5c-6c9e3d101475.png)

任何指导表示赞赏

```
Error: ENOENT: no such file or directory, open '../components/global-assign-hook-component/core/hook.js'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at loadPluginsAsString (C:\Users\z\Downloads\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\plugins-manager.js:38:27)
    at loadPluginsAsStringWithCache (C:\Users\z\Downloads\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\plugins-manager.js:21:33)
    at processRealtime (C:\Users\z\Downloads\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:191:36)
    at processJavaScriptResponse (C:\Users\z\Downloads\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:159:9)
    at Object.process (C:\Users\z\Downloads\ast-hook-for-js-RE-master\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:54:13)
    at Object.beforeSendResponse (C:\Users\z\Downloads\ast-hook-for-js-RE-master\src\proxy-server\rules.js:6:35)
    at beforeSendResponse.next (<anonymous>)
    at onFulfilled (C:\Users\z\Downloads\ast-hook-for-js-RE-master\node_modules\co\index.js:65:19)
    at C:\Users\z\Downloads\ast-hook-for-js-RE-master\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\z\Downloads\ast-hook-for-js-RE-master\node_modules\co\index.js:50:10)
    at toPromise (C:\Users\z\Downloads\ast-hook-for-js-RE-master\node_modules\co\index.js:118:63)
    at next (C:\Users\z\Downloads\ast-hook-for-js-RE-master\node_modules\co\index.js:99:29)
    at onFulfilled (C:\Users\z\Downloads\ast-hook-for-js-RE-master\node_modules\co\index.js:69:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '../components/global-assign-hook-component/core/hook.js'
}
```

**Comment by drain** [comment]
我很愚蠢，在阅读错误后我意识到我需要从正确的目录执行。

**Comment by jiaweike** [comment]
@drain could you pls tell me how to deal with this issue? I got the same issue.
