### ISSUE TITLE
Babel 报错，有几千个类似这种的

### ISSUE THREAD

**Issue by Cyhlnj** [CC11001100/ast-hook-for-js-RE#3]
`> 1 | window.҇=$("Ƀ")
    |        ^
    at Parser._raise (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:748:17)
    at Parser.raiseWithData (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:741:17)
    at Parser.raise (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:735:17)
    at Parser.getTokenFromCode (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:8423:16)
    at Parser.nextToken (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:7889:12)
    at Parser.next (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:7819:10)
    at Parser.eat (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:7824:12)
    at Parser.parseSubscript (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:10195:63)
    at Parser.parseSubscripts (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:10167:19)
    at Parser.parseExprSubscripts (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:10156:17) {
  loc: Position { line: 1, column: 7 },
  pos: 7,
  code: 'BABEL_PARSE_ERROR'
}
SyntaxError: unknown: Unexpected character '҈' (1:7)

> 1 | window.҈=$("Ʉ")
    |        ^
    at Parser._raise (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:748:17)
    at Parser.raiseWithData (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:741:17)
    at Parser.raise (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:735:17)
    at Parser.getTokenFromCode (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:8423:16)
    at Parser.nextToken (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:7889:12)
    at Parser.next (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:7819:10)
    at Parser.eat (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:7824:12)
    at Parser.parseSubscript (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:10195:63)
    at Parser.parseSubscripts (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:10167:19)
    at Parser.parseExprSubscripts (/Users/cyh/WebstormProjects/ast-hook-for-js-RE/node_modules/@babel/parser/lib/index.js:10156:17) {
  loc: Position { line: 1, column: 7 },
  pos: 7,
  code: 'BABEL_PARSE_ERROR'
}
SyntaxError: unknown: Unexpected character '҉' (1:7)`

**Comment by CC11001100** [comment]
已私下沟通解决了，是因为中午提交的代码有问题，代码已经回退，此问题不再存在。

项目有人用的话不能那么随意的提交底代码了。。。。
