### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by HrOice** [CC11001100/ast-hook-for-js-RE#33]
PayloadTooLargeError: request entity too large
    at readStream (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/raw-body/index.js:155:17)
    at getRawBody (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/raw-body/index.js:108:12)
    at read (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/body-parser/lib/read.js:77:3)
    at rawParser (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/body-parser/lib/types/raw.js:81:5)
    at Layer.handle [as handle_request] (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/express/lib/router/index.js:317:13)
    at /Users/macbook/develop/ast-hook-for-js-RE/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/macbook/develop/ast-hook-for-js-RE/node_modules/express/lib/middleware/init.js:40:5)

是rs的js太大了嘛

![image](https://user-images.githubusercontent.com/12363835/185064869-5e9c7aca-6832-4e8b-96ec-c93f4040a285.png)

**Comment by hackerconding** [comment]
我也遇到了这个问题
