### ISSUE TITLE
抓取请求过程中有js报错

### ISSUE THREAD

**Issue by wangxu6868** [CC11001100/ast-hook-for-js-RE#47]
Error: ENOENT: no such file or directory, open 'C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js'
at Object.openSync (node:fs:582:18)
at Object.readFileSync (node:fs:461:35)
at loadPluginsAsString (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:41:27)
at loadPluginsAsStringWithCache (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:22:33)
at processRealtime (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:195:36)
at processJavaScriptResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:167:9)
at Object.process (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:54:13)
at Object.beforeSendResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\rules.js:6:35)
at beforeSendResponse.next ()
at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:65:19)
at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
at new Promise ()
at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
at toPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:118:63)
at next (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:99:29)
at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:69:7)
at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
at new Promise ()
at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
at createPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:30:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errno: -4058,
code: 'ENOENT',
syscall: 'open',
path: 'C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js'
}
[AnyProxy Log][2024-05-14 09:25:26]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:26]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:26]: received https CONNECT request mon.zijieapi.com
[AnyProxy Log][2024-05-14 09:25:26]: will forward to local https server
[AnyProxy Log][2024-05-14 09:25:26]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:27]: received https CONNECT request helpdesk.bytedance.com
[AnyProxy Log][2024-05-14 09:25:27]: will forward to local https server
[AnyProxy Log][2024-05-14 09:25:27]: [internal https]proxy server for helpdesk.bytedance.com established
[AnyProxy Log][2024-05-14 09:25:27]: received request to: GET helpdesk.bytedance.com/sites/standalone/helpcenter_pc/?header_toggle=true&extra_persistent_params=%7B%22webId%22:%227368318630956762660%22,%22logId%22:%222024051409252452E2ADD97EB77F3798C1%22,%22url%22:%22https://www.toutiao.com/?wid=1715570387499%22,%22cf_biz_id%22:%2235%22,%22user_agent%22:%22Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/124.0.0.0%20Safari/537.36%22%7D&host_app_version=&host_app_model=&channel=undefined&biz_id=35&app_id=24&web_id=7368318630956762660&app_name=toutiao_web&render_width=408&render_height=570&is_in_frame=1&theme=light&from=https://www.toutiao.com/?wid=1715570387499
[AnyProxy Log][2024-05-14 09:25:27]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:28]: received request to: GET [www.toutiao.com/sw.js](http://www.toutiao.com/sw.js)
Error: ENOENT: no such file or directory, open 'C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js'
at Object.openSync (node:fs:582:18)
at Object.readFileSync (node:fs:461:35)
at loadPluginsAsString (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:41:27)
at loadPluginsAsStringWithCache (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:22:33)
at processRealtime (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:195:36)
at processJavaScriptResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:163:9)
at Object.process (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:54:13)
at Object.beforeSendResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\rules.js:6:35)
at beforeSendResponse.next ()
at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:65:19)
at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
at new Promise ()
at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
at toPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:118:63)
at next (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:99:29)
at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:69:7)
at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
at new Promise ()
at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
at createPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:30:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errno: -4058,
code: 'ENOENT',
syscall: 'open',
path: 'C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js'
}

加载网站js时, 发现了两条类似报错

**Comment by wangxu6868** [comment]
Error: ENOENT: no such file or directory, open 'C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js'
    at Object.openSync (node:fs:582:18)
    at Object.readFileSync (node:fs:461:35)
    at loadPluginsAsString (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:41:27)
    at loadPluginsAsStringWithCache (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:22:33)
    at processRealtime (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:195:36)
    at processJavaScriptResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:167:9)
    at Object.process (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:54:13)
    at Object.beforeSendResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\rules.js:6:35)
    at beforeSendResponse.next (<anonymous>)
    at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:65:19)
    at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
    at toPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:118:63)
    at next (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:99:29)
    at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:69:7)
    at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
    at createPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:30:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\王旭\\Desktop\\frontEndTools\\ast-hook-for-js-RE\\src\\proxy-server\\src\\components\\global-assign-hook-component\\core\\hook.js'
}
[AnyProxy Log][2024-05-14 09:25:26]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:26]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:26]: received https CONNECT request mon.zijieapi.com
[AnyProxy Log][2024-05-14 09:25:26]: will forward to local https server
[AnyProxy Log][2024-05-14 09:25:26]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:27]: received https CONNECT request helpdesk.bytedance.com
[AnyProxy Log][2024-05-14 09:25:27]: will forward to local https server
[AnyProxy Log][2024-05-14 09:25:27]: [internal https]proxy server for helpdesk.bytedance.com established
[AnyProxy Log][2024-05-14 09:25:27]: received request to: GET helpdesk.bytedance.com/sites/standalone/helpcenter_pc/?header_toggle=true&extra_persistent_params=%7B%22webId%22:%227368318630956762660%22,%22logId%22:%222024051409252452E2ADD97EB77F3798C1%22,%22url%22:%22https://www.toutiao.com/?wid=1715570387499%22,%22cf_biz_id%22:%2235%22,%22user_agent%22:%22Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/124.0.0.0%20Safari/537.36%22%7D&host_app_version=&host_app_model=&channel=undefined&biz_id=35&app_id=24&web_id=7368318630956762660&app_name=toutiao_web&render_width=408&render_height=570&is_in_frame=1&theme=light&from=https://www.toutiao.com/?wid=1715570387499
[AnyProxy Log][2024-05-14 09:25:27]: received request to: POST mon.zijieapi.com/monitor_browser/collect/batch/?biz_id=toutiao_web_pc
[AnyProxy Log][2024-05-14 09:25:28]: received request to: GET www.toutiao.com/sw.js
Error: ENOENT: no such file or directory, open 'C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js'
    at Object.openSync (node:fs:582:18)
    at Object.readFileSync (node:fs:461:35)
    at loadPluginsAsString (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:41:27)
    at loadPluginsAsStringWithCache (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\plugins-manager.js:22:33)
    at processRealtime (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:195:36)
    at processJavaScriptResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:163:9)
    at Object.process (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\components\global-assign-hook-component\core\global-assign-hook-component-main.js:54:13)
    at Object.beforeSendResponse (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\rules.js:6:35)
    at beforeSendResponse.next (<anonymous>)
    at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:65:19)
    at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
    at toPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:118:63)
    at next (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:99:29)
    at onFulfilled (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:69:7)
    at C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:50:10)
    at createPromise (C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\node_modules\co\index.js:30:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\王旭\\Desktop\\frontEndTools\\ast-hook-for-js-RE\\src\\proxy-server\\src\\components\\global-assign-hook-component\\core\\hook.js'
}



加载网站js时, 发现了两条类似报错

**Comment by leleleocc** [comment]
路劲有问题，但是我不知道怎么改

**Comment by wangxu6868** [comment]
@leleleocc  C:\Users\王旭\Desktop\frontEndTools\ast-hook-for-js-RE\src\proxy-server\src\components\global-assign-hook-component\core\hook.js 这个文件有一个路径不对, 需要改。 好像是加个./啥的 具体忘了

**Comment by lengmianzz** [comment]
把components文件夹移动到ast-hook-for-js-RE\src目录下面

**Comment by wangxu6868** [comment]
thanks&nbsp;
